version: '3'

networks: 
    bibbox-default-network:
        external: true

services:
    dspace:
        container_name: dspace
        image: dspace/dspace:dspace-7_x-test
        restart: unless-stopped
        links:
            - dspacedb:dspacedb
            - dspacesolr:dspacesolr
        environment:
            - REST_HOST=localhost
            - UI_HOST=dspace-angular
        networks: 
            - bibbox-default-network
        ports:
            - 8080:8080
            - 8009:8009
        stdin_open: true
        tty: true
        volumes:
            - ./data/assetstore:/dspace/assetstore
            - ./images/ROOT:/usr/local/tomcat/webapps/ROOT
            - ./images/configs/local.cfg.template.local:/dspace/config/local.cfg.template
            - ./images/configs/sed.sh:/dspace/config/sed.sh
            - ./images/configs/startup.sh:/dspace/config/startup.sh
            - ./images/rel.xml:/dspace/config/relationship-types.xml
        entrypoint:
            - /bin/bash
            - '-c'
            - |
                while (!</dev/tcp/dspacedb/5432) > /dev/null 2>&1; do sleep 1; done;
                bash /dspace/config/sed.sh
                /dspace/bin/dspace database migrate
                /dspace/bin/dspace create-administrator -e test@test.edu -f admin -l user -p admin -c en
                /dspace/bin/dspace dsrun org.dspace.app.util.InitializeEntities -f /dspace/config/relationship-types.xml
                sed -i '/name-map collection-handle="default".*/a \\n <name-map collection-handle="123456789/3" submission-name="Publication"/> \
                    <name-map collection-handle="123456789/4" submission-name="Publication"/> \
                    <name-map collection-handle="123456789/281" submission-name="Publication"/> \
                    <name-map collection-handle="123456789/5" submission-name="Publication"/> \
                    <name-map collection-handle="123456789/8" submission-name="OrgUnit"/> \
                    <name-map collection-handle="123456789/6" submission-name="Person"/> \
                    <name-map collection-handle="123456789/279" submission-name="Person"/> \
                    <name-map collection-handle="123456789/7" submission-name="Project"/> \
                    <name-map collection-handle="123456789/280" submission-name="Project"/> \
                    <name-map collection-handle="123456789/28" submission-name="Journal"/> \
                    <name-map collection-handle="123456789/29" submission-name="JournalVolume"/> \
                    <name-map collection-handle="123456789/30" submission-name="JournalIssue"/>' /dspace/config/item-submission.xml
                catalina.sh run
    
    dspace-angular:
        container_name: dspace-angular
        environment:
            - DSPACE_HOST=dspace-angular
            - DSPACE_NAMESPACE=/
            - DSPACE_PORT=4000
            - DSPACE_SSL="false"
            - DSPACE_REST_HOST=localhost
            - DSPACE_REST_PORT=8080
            - DSPACE_REST_NAMESPACE=/server
            - DSPACE_REST_SSL="false"
        image: dspace/dspace-angular-cat:latest
        build:
            context: ./images/src/
            dockerfile: Dockerfile
        
        networks:
            - bibbox-default-network
        depends_on:
            - dspace
        links:
            - dspace:dspace
        ports:
           - 4000:4000
           - 9876:9876
        stdin_open: true
        tty: true

    dspacedb:
        container_name: dspace-db
        image: dspace/dspace-postgres-pgcrypto:loadsql
        restart: unless-stopped
        environment:
            - PGDATA=/pgdata
            - LOADSQL=https://github.com/DSpace-Labs/AIP-Files/releases/download/demo-entities-data/dspace7-entities-2021-04-14.sql
        networks:
            - bibbox-default-network
        ports:
            - 5432:5432
        stdin_open: true
        tty: true
        volumes: 
            - ./data/pgdata:/pgdata
    
    dspacesolr:
        container_name: dspacesolr
        image: solr:8.8
        restart: unless-stopped
        networks:
            - bibbox-default-network
        ports:
            - 8983:8983
        stdin_open: true
        tty: true
        working_dir: /var/solr/data
        volumes:
            - ./images/configs/solr/authority:/opt/solr/server/solr/configsets/authority
            - ./images/configs/solr/oai:/opt/solr/server/solr/configsets/oai
            - ./images/configs/solr/search:/opt/solr/server/solr/configsets/search
            - ./images/configs/solr/statistics:/opt/solr/server/solr/configsets/statistics
            # Keep Solr data directory between reboots
            - ./data/solr_data:/var/solr/data
        entrypoint:
            - /bin/bash
            - '-c'
            - |
                init-var-solr
                precreate-core authority /opt/solr/server/solr/configsets/authority
                precreate-core oai /opt/solr/server/solr/configsets/oai
                precreate-core search /opt/solr/server/solr/configsets/search
                precreate-core statistics /opt/solr/server/solr/configsets/statistics

                exec solr -f
